#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/ibm-container-resource
cat > "$payload" <&0
initial_version=$(jq -r '.source.version // ""' < "$payload")
environment=$(jq -r '.source.environment // ""' < "$payload")
type=$(jq -r '.source.type // "default"' < "$payload")
if [ -n "${environment}" ] || [[ "${environment}" == "ng" ]]
then
    environment=${environment}.
fi
request_uri=$(jq -r '.source.uri // "https://containers.'${environment}'bluemix.net/v1/kube-versions"' < "$payload")

ARMADA_VERSION_JSON=$(curl "$request_uri")

if [[ "${type}" == "latest" ]]
then
    VERSION=$(echo "$ARMADA_VERSION_JSON" | jq -r '.[-1] | (.major|tostring) + "." + (.minor|tostring) + "." + (.patch|tostring)')
elif [[ "${type}" == "oldest" ]]
then
    VERSION=$(echo "$ARMADA_VERSION_JSON" | jq -r '.[0] | (.major|tostring) + "." + (.minor|tostring) + "." + (.patch|tostring)')
else
    VERSION=$(echo "$ARMADA_VERSION_JSON" | jq -r '.[] | select(.default == true ) | (.major|tostring) + "." + (.minor|tostring) + "." + (.patch|tostring)')
fi

if dpkg --compare-versions "${VERSION}" "le" "${initial_version}"
then
    echo "[]" >&3
else
    echo ${VERSION} | jq -R '.' | jq -s "map({number: .})" >&3
fi