#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=${1}
mkdir -p "${destination}"

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/ibm-container-resource
cat > "$payload" <&0
VERSION=$(jq -r '.version.number // ""' < "$payload")

echo ${VERSION} > "${destination}"/number

jq -n "{
  version: {number: $(echo ${VERSION} | jq -R .)},
  metadata: []
}" >&3