#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=${1}
mkdir -p ${destination}

# for jq
PATH=/usr/local/bin:$PATH

payload=$TMPDIR/ibm-container-resource
cat > $payload <&0
previous_version=$(jq -r '.version.number // ""' < $payload)
environment=$(jq -r '.source.environment // ""' < $payload)
if [ -n "${environment}" ]
then
    environment=${environment}.
fi

ARMADA_VERSION_JSON=$(curl https://containers."${environment}"bluemix.net/v1/kube-versions)

VERSION=$(echo "$ARMADA_VERSION_JSON" | jq -r '.[] | select(.default == true ) | (.major|tostring) + "." + (.minor|tostring) + "." + (.patch|tostring)')

if [ -z "${VERSION}" ]
then
    VERSION=0.0.0
fi

echo ${VERSION} > ${destination}/number

jq -n "{
  version: {number: $(echo ${VERSION} | jq -R .)},
  metadata: []
}" >&3