resource_types:
- name: ibm-container-1
  type: docker-image
  source:
    repository: bluebosh/ibm-container-resource
    tag: latest

resources:
- name: ibm-container-stage
  type: ibm-container-1
  source:
    environment: stage1
    type: latest
    version: 1.9.1

jobs:
- name: check-ibm-container-version
  plan:
  - aggregate:
    - get: ibm-container-stage
      trigger: true
  - task: get-ibm-container-version
    config:
      platform: linux
      image_resource: { type: docker-image, source: { repository: bluebosh/ibm-container-resource, tag: latest } }
      inputs:
      - name: ibm-container-stage
      run:
        path: /bin/bash
        args:
        - -c
        - |
          #!/bin/bash

          cat ibm-container-stage/number